name: Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Gen LFS Cache Key File
      run: git lfs ls-files -l > lsf-cache-key
    - name: Cache Git LFS
      uses: actions/cache@v1
      id: cache-git-lfs
      with:
        path: .git/lfs
        key: ${{ runner.os }}-${{ hashFiles('**/lsf-cache-key') }}
    - name: Git LFS
      if: steps.cache-git-lfs.cache-hit != 'true'
      run: git lfs pull
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        pman test
